sudo service oozie start
sudo service hive-metastore start
sudo service hive-server2 start
sudo service impala-state-store start
sudo service impala-server start
sudo service hue start
sudo service impala-catalog start
sudo service hadoop-yarn-nodemanager start
sudo service hadoop-mapreduce-historyserver start
sudo service hadoop-yarn-resourcemanager start
sudo service spark-master start
sudo service spark-worker start
sudo service hbase-master start
sudo service hbase-regionserver start
